### ISSUE TITLE
File Downloads urls are not working (committee page)

### ISSUE THREAD

**Issue by hmanalai** [BCStudentSoftwareDevTeam/urcpp#108]
**[Original report](https://bitbucket.org/laborstudents/urcpp-flask/issue/108) by Guillermo ramos (Bitbucket: [guillermo_ramos](https://bitbucket.org/guillermo_ramos), GitHub: [memo330179](https://github.com/memo330179)).**

----------------------------------------

The file downloads in URCPP are not working. When trying to download documents on the committee page we get the following error.

```python
Traceback (most recent call last):
  File "/home/ubuntu/workspace/venv/lib/python2.7/site-packages/flask/app.py", line 2000, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/ubuntu/workspace/venv/lib/python2.7/site-packages/flask/app.py", line 1991, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/home/ubuntu/workspace/venv/lib/python2.7/site-packages/flask/app.py", line 1567, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ubuntu/workspace/venv/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/workspace/venv/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/workspace/venv/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ubuntu/workspace/venv/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/workspace/venv/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ubuntu/workspace/api/pages/download.py", line 13, in document
    if request.method == GET:
NameError: global name 'GET' is not defined
```

**Comment by hmanalai** [comment]
**Original comment by Katelyn Adams (Bitbucket: [paesh1997](https://bitbucket.org/paesh1997), GitHub: [paesh1997](https://github.com/paesh1997)).**

----------------------------------------

[http://urcpp-2-adamska.c9users.io:8081/committee/allBudgets](http://urcpp-2-adamska.c9users.io:8081/committee/allBudgets) budget download doesnt work either

**Comment by hmanalai** [comment]
**Original comment by Katelyn Adams (Bitbucket: [paesh1997](https://bitbucket.org/paesh1997), GitHub: [paesh1997](https://github.com/paesh1997)).**

----------------------------------------

already resolved
