### ISSUE TITLE
Althea Webb gets an error

### ISSUE THREAD

**Issue by hmanalai** [BCStudentSoftwareDevTeam/urcpp#42]
**[Original report](https://bitbucket.org/laborstudents/urcpp-flask/issue/42) by Scott Heggen (Bitbucket: [sheggen](https://bitbucket.org/sheggen), GitHub: [sheggen](https://github.com/sheggen)).**

----------------------------------------

When Althea accesses ~/webba/committee she gets a "Dict object is not callable" error (or similar).

**Comment by hmanalai** [comment]
**Original comment by Scott Heggen (Bitbucket: [sheggen](https://bitbucket.org/sheggen), GitHub: [sheggen](https://github.com/sheggen)).**

----------------------------------------

Exact error:

TypeError

TypeError: 'dict' object is not callable

Traceback (most recent call last)

    File "/home/heggens/urcpp-flask/venv/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__

return self.wsgi_app(environ, start_response)

    File "/home/heggens/urcpp-flask/venv/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app

response = self.make_response(self.handle_exception(e))

    File "/home/heggens/urcpp-flask/venv/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception

**Comment by hmanalai** [comment]
**Original comment by Guillermo ramos (Bitbucket: [guillermo_ramos](https://bitbucket.org/guillermo_ramos), GitHub: [memo330179](https://github.com/memo330179)).**

----------------------------------------

This seems like an issue that has long been forgotten. Marking it wontfix.
